apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      nodeSelector:
        role: build
      containers:
      - name: app-container
        image: your-dockerhub-username/your-app:latest
        ports:
        - containerPort: 3000

