apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: default
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80         # Port exposed inside the cluster
      targetPort: 3000 # Must match containerPort from your Deployment
      nodePort: 30080  # External port for accessing from outside

