apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 80          # Service port
      targetPort: 3000  # Container port
      nodePort: 30080   # External port you can access on the master node


